### ISSUE TITLE
Add https://searx.tunkki.xyz

### ISSUE THREAD

**Issue by larikuistio** [searx/searx-instances#111]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
You picked both of the bot protection part. Which one do you deploy? With a bot protection or not.

**Comment by larikuistio** [comment]
> You picked both of the bot protection part. Which one do you deploy? With a bot protection or not.

Oh, I didn't understand that I'm not supposed to tick the second one. I have filtron and I updated the issue

**Comment by dalf** [comment]
in your settings.yml, I think you have this:
```yaml
result_proxy:
    url: http://searx.tunkki.xyz/morty
```

it should be http**s**://searx.tunkki.xyz/morty (https instead of http).

---

Currently there is no limit to the number of JSON requests.

I strongly advice you to add this your rules.json (filtron) to limit these requests:  https://github.com/searx/searx-docker/blob/f2736e1e19f88d7f94cb91114027d9bcd381479e/rules.json#L112-L123
(you can just use the whole file if you want)

**Comment by larikuistio** [comment]
Thanks for pointing those out, they should be fixed now. But there actually already was a rule for json request in rules.json, just with "interval" being 121 and "limit" 4, and it was also missing the "aggregations" part.

**Comment by larikuistio** [comment]
Any update on this?

**Comment by unixfox** [comment]
You may adjust your filtron rules because they aren't limiting the RSS/JSON requests.

You can see an example here: https://searx.tunkki.xyz/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json
Refresh 5 times, and it should be blocked, but it's not the case with your instance.

Also, on a personal note, your instance feels really slow to respond compared to the other instances in this GitHub repository.

**Comment by larikuistio** [comment]
The rate limit seems to work now, there was a small misconfiguration in nginx. My bad

I'm not really sure what I'm supposed to do to get a better rating here, I only get an E rating atm: https://cryptcheck.fr/https/searx.tunkki.xyz

It doesn't really point out any issues, and I get an A rating with this SSL Labs test: https://www.ssllabs.com/ssltest/analyze.html?d=tunkki.xyz&s=46.165.214.65&latest

I can try to see if there's something else using too much resources, that could explain the slowness

**Comment by unixfox** [comment]
You are missing [HSTS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security), that's why you got an E rating.

**Comment by larikuistio** [comment]
Okay that should be fixed now, I got an A+ rating after adding that to nginx configuration.
