### ISSUE TITLE
Check https://searx.prvcy.eu

### ISSUE THREAD

**Issue by dontlookmysnake** [searx/searx-instances#112]
https://searx.prvcy.eu is connecting to an external domain (selfhosting.rocks), and when I tried to visit that site, Firefox warned me the site was potentially dangerous.

**Comment by unixfox** [comment]
Can you prove that? Using a screenshot for example. I don't see any request related to that website.

**Comment by dontlookmysnake** [comment]
Sure.

![searxprvcyeu](https://user-images.githubusercontent.com/77842293/106038175-7efdef80-60cf-11eb-9493-df2d0ab68224.png)

I don't know if everything's fine with this instance, maybe it is, I just want to make sure it's safe to use.

**Comment by unixfox** [comment]
Look at the network tab in the developer tabs instead of using ublock for inspecting the packets to foreign domains.

You will see that everything is clean and all the requests are done on the same domain. Moreover, on searx.space didn't detect any external script because the instance has a `A` green letter.

**Comment by dalf** [comment]
```
$ nslookup searx.prvcy.eu
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
searx.prvcy.eu	canonical name = general.selfhosting.rocks.
Name:	general.selfhosting.rocks
Address: 95.216.165.156
Name:	general.selfhosting.rocks
Address: 2a01:4f9:c010:1edb::1
```

See also https://viewdns.info/dnsrecord/?domain=searx.prvcy.eu

**Comment by dalf** [comment]
More in detail : 
* Firefox displays a certificate problem for `selfhosting.rocks`, because the certificated is about a random subdomain. 
* The debug console of Firefox doesn't show the connection to `selfhosting.rocks`, that's normal, the requested domain name is `searx.prvcy.eu`.
* uBlock Origin reports a connection to `selfhosting.rocks`, because of the DNS configuration `searx.prvcy.eu	canonical name = general.selfhosting.rocks.`. See https://en.wikipedia.org/wiki/UBlock_Origin#CNAME-uncloaking_third-party_trackers_in_Firefox

In the end, I don't think there is a problem.
