### ISSUE TITLE
Add https://privatesearch.app

### ISSUE THREAD

**Issue by danijel-orsolic** [searx/searx-instances#113]
Hello, thank you for a great project. I'd like to add https://privatesearch.app instance to searx.space.

* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/).
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

At present there are small modifications to a copy of the default oscar theme (oscar-mod) to provide a bit fresher color scheme, a logo and some minor adjustments. I might modify this further in the future. 

The source code of all of the modifications is at https://gitlab.com/zenterial/privatesearch.app which is also mentioned in the footer and on the about page besides the original github repository. It includes the oscar-mod files, a simple build script to pull the original searx from its repository and build the container with modifications, and kubernetes manifests.

Instance is running in a highly available setup on a kubernetes cluster with currently three searx, morty and filtron instances. I've been using it as my default search engine for over a month now without issues so I'd like to see how it fares if more people use it.

Thank you!

**Comment by unixfox** [comment]
Interesting setup, I've almost the same setup as you. I'm also running Searx on Kubernetes: https://github.com/unixfox/k8s/tree/master/charts/searx for https://searx.be. Just be aware that my chart is not yet designed for everyone, I'll publish a generic one once I'll have some free time.

Before adding your instance I would like to point out some modifications that you could do:
- Your filtron rules are too weak, use the one from this repository for blocking more efficiently the bots: https://github.com/searx/searx-docker/blob/master/rules.json
- Running filtron with 3 replicas mean that you are essentially deploying 3 different blocking system that have its own limit and doesn't know each other.
Let's take an example, in your filtron rules you have a limit of 5 requests with an interval of 10 for "IP limit" rule. By running 3 instances of filtron you are basically triple the amount of allowed requests. Instead of 5 requests it's 15 requests.
I would recommend you to run filtron with just 1 replica. I know it's not high availability friendly but filtron wasn't designed with HA in mind, so we unfortunately have to deal with it if you want to enforce your rules properly.
- Why are you writing the full domain in https://gitlab.com/zenterial/privatesearch.app/-/blob/master/kubernetes/filtron-deployment.yaml#L42? Do you know that you can just write "searx:8080"?

Side note we can still access to your settings.yml: https://gitlab.com/zenterial/privatesearch.app/-/blob/05a077a908f75edcbd46be3b6f6e4923cb13a4e9/docker-build/settings.yml

**Comment by danijel-orsolic** [comment]
Nice, kube rocks! Will test out your helm chart on a separate test cluster. 

I've commited and deployed your suggestions.

Understood about multiple filtron replicas. I suppose values might be adjusted to account for the tripling effect, but one replica is quite alright as well.

The full domain may have been just ignorance or habit, indeed it works with just searx:8080 since it's in the same namespace.

As for the settings file in the history, that's fine, I changed the live secret key and the rest of the settings are standard stuff anyway.

Thank you!

**Comment by dalf** [comment]
Some notes : 

About https://observatory.mozilla.org/analyze/privatesearch.app?third-party=false , there are two missing headers : 
* CSP see https://github.com/searx/searx-docker/blob/f2736e1e19f88d7f94cb91114027d9bcd381479e/Caddyfile#L77-L84
* X-Frame-Options, see https://github.com/searx/searx-docker/blob/f2736e1e19f88d7f94cb91114027d9bcd381479e/Caddyfile#L44

About https://cryptcheck.fr/https/privatesearch.app , the grade is C because DH key exchange.

Nothing mandatory.

**Comment by danijel-orsolic** [comment]
Fixed both issues now, should be all A+. Thanks!
