### ISSUE TITLE
Add https://swag.pw/

### ISSUE THREAD

**Issue by derekslenk** [searx/searx-instances#116]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hi,

Everything is ok on the antibot protection side but two things I recommend you to fix:
- The IPv6 address associated with your instance doesn't respond (`2600:1f16:f08:4402:fd02:8b0e:72e9:5c15`). This is an issue because searx.space doesn't check the broken instances.
- Your TLS configuration is somewhat outdated: https://cryptcheck.fr/https/swag.pw. I recommend you this website for adjusting the TLS configuration: https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.6
Remove the ciphers that cryptcheck doesn't want you to use though.

**Comment by derekslenk** [comment]
> 
> 
> Hi,
> 
> Everything is ok on the antibot protection side but two things I recommend you to fix:
> 
>     * The IPv6 address associated with your instance doesn't respond (`2600:1f16:f08:4402:fd02:8b0e:72e9:5c15`). This is an issue because searx.space doesn't check the broken instances.
> 
>     * Your TLS configuration is somewhat outdated: https://cryptcheck.fr/https/swag.pw. I recommend you this website for adjusting the TLS configuration: https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=intermediate&openssl=1.1.1d&guideline=5.6
>       Remove the ciphers that cryptcheck doesn't want you to use though.

Whoa, saw this way too late. Will work on suggestions.

**Comment by derekslenk** [comment]
@unixfox - Sorry it has taken so long, I am passing the SSL labs verification, waiting to be able to run cryptcheck again.

https://www.ssllabs.com/ssltest/analyze.html?d=swag.pw&s=2600%3a1f16%3af08%3a4402%3afd02%3a8b0e%3a72e9%3a5c15

**Comment by derekslenk** [comment]
I am going to close this, I seem to have broken everything.

I will be back once I learn IPv6 and nginx better

**Comment by derekslenk** [comment]
I do believe we are good now.
