### ISSUE TITLE
Add https://searx.roughs.ru/

### ISSUE THREAD

**Issue by buvanenko** [searx/searx-instances#118]
* [x] It is my instance.
* [ ] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [ ] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [x] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

You may adjust your NGINX configuration because your TLS configuration is not modern enough and considered as a bad practice for security. Your TLS score is available here: https://cryptcheck.fr/https/searx.roughs.ru

You may look into this website for adjusting your TLS configuration: https://ssl-config.mozilla.org/.

This is not mandatory and if you don't want to make any adjustment, just reply to my message stating that you won't make any changes about that.

**Comment by buvanenko** [comment]
@unixfox, I don't want to make any changes.

**Comment by return42** [comment]
@buvanenko FYI

- https://github.com/searxng/searx-instances/discussions/336
