### ISSUE TITLE
Add https://search.egeg.fun

### ISSUE THREAD

**Issue by cofob** [searx/searx-instances#120]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by ferPFlores** [comment]
your certificate isn't working and redirects to another page

**Comment by cofob** [comment]
@ferPFlores 
![1](https://user-images.githubusercontent.com/49928332/110815720-97daf280-8282-11eb-9e2b-fee5d7c29bbf.png)
Its a wildcard certificate and 301 redirect to https side.

**Comment by unixfox** [comment]
It's advised to have more hardened filtron rules from here: https://github.com/searx/searx-docker/blob/master/rules.json. You aren't using them because I'm able to do an "infinite" amount of requests to CSV/JSON/RSS type results. Here is an example: https://search.egeg.fun/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

Moreover, your TLS configuration is not considered secure. You may improve it and see your TLS configuration score here: https://cryptcheck.fr/https/search.egeg.fun.

These were just advices, if you don't want to apply them then feel free to reply here by confirming it.
