### ISSUE TITLE
Add https://methylcraft.com/search

### ISSUE THREAD

**Issue by vinc3nz** [searx/searx-instances#123]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

It's advised to use more hardened filtron rules from here: https://github.com/searx/searx-docker/blob/master/rules.json. You aren't using them because I'm able to do an "infinite" amount of requests to CSV/JSON/RSS type results. Here is an example: https://methylcraft.com/search/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

Moreover, on a personal note the privacy community don't like Cloudflare because it is considered bad due to the fact that Cloudflare can see all the traffic between the visitors and your server. I recommend you to disable Cloudflare.

These were just advices, if you don't want to apply them then feel free to reply here by confirming it.

**Comment by vinc3nz** [comment]
Its ok, add the instance please
