### ISSUE TITLE
Add https://searx.failnet.xyz

### ISSUE THREAD

**Issue by 0x00009b** [searx/searx-instances#127]
* [X] It is my instance.
* [X] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [X] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

It's advised to use more hardened filtron rules from here: https://github.com/searx/searx-docker/blob/master/rules.json. You aren't using them because I'm able to do an "infinite" amount of requests to CSV/JSON/RSS type results. Here is an example: https://searx.failnet.xyz/search?category_general=1&q=ok&pageno=1&time_range=None&language=fr-FR&format=json

Moreover, on a personal note the privacy community don't like Cloudflare because it is considered bad due to the fact that Cloudflare can see all the traffic between the visitors and your server. I recommend you to disable Cloudflare.

These were just advices, if you don't want to apply them then feel free to reply here by confirming it then I'll go ahead and add your instance to the public list.

**Comment by z3r0n3t** [comment]
understood I will disable cloudflare and work on setting up a stricter filtron policy

**Comment by unixfox** [comment]
Searx is not served anymore on this instance. Reopen if this is fixed.
