### ISSUE TITLE
Add https://search.fshm.in

### ISSUE THREAD

**Issue by demonshreder** [searx/searx-instances#128]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Which item do you choose between having a bot protection or not? You picked both, and you just need to pick one of them.

**Comment by demonshreder** [comment]
Sorry I thought it was like disclaimer. I have filtron running on the server.

**Comment by unixfox** [comment]
It's advised to use more hardened filtron rules from here: https://github.com/searx/searx-docker/blob/master/rules.json. You aren't using them because I'm able to do an "infinite" amount of requests to CSV/JSON/RSS type results. Here is an example: https://search.fshm.in/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

Moreover, your TLS configuration is not considered secure. You may improve it and see your TLS configuration score here: https://cryptcheck.fr/https/search.fshm.in.

These were just advices, if you don't want to apply them then feel free to reply here by confirming it then I'll go ahead and add your instance to the public list.

**Comment by demonshreder** [comment]
Hi @unixfox, I dunno what seems to be the issue with SSL rules, I have added Mozilla Modern recommendations (https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1d&guideline=5.6) and it scores A+ on SSL Labs test - https://www.ssllabs.com/ssltest/analyze.html?d=search.fshm.in&hideResults=on

Thanks for the hardened filtron rules, I have added it to the filtron. 

Please check and update, I am happy to make this instance more reliable for public use.

**Comment by unixfox** [comment]
> I dunno what seems to be the issue with SSL rules, I have added Mozilla Modern recommendations ([ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1d&guideline=5.6](https://ssl-config.mozilla.org/#server=nginx&version=1.17.7&config=modern&openssl=1.1.1d&guideline=5.6)) and it scores A+ on SSL Labs test - [ssllabs.com/ssltest/analyze.html?d=search.fshm.in&hideResults=on](https://www.ssllabs.com/ssltest/analyze.html?d=search.fshm.in&hideResults=on)

That's great that you used mozilla ssl generator, but it disables TLS 1.2 which is still secure as of today and cryptcheck doesn't support TLS 1.3 yet. We are using cryptcheck because we don't consider ssllabs trustworthy for the security of the public instances (more on that here: https://github.com/searx/searx-stats2/issues/10#issuecomment-572003677). Could you enable TLS 1.2? You can use the intermediate config and just remove the ciphers that cryptcheck consider as insecure.

> Thanks for the hardened filtron rules, I have added it to the filtron.

It seems like the filtron rules doesn't work, refresh 6 times this page: https://search.fshm.in/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json and it should block further requests if the rules are applied properly.
I can't find the github issue where someone had a similar issue to you, but it was related to the /searx path. I think you need to tweak the filtron rules for that because those rules are when Searx is exposed on the root path (`/`) and not on the subpath `/searx`.

**Comment by demonshreder** [comment]
Hi @unixfox  I have updated the HTTPS rules to accommodate TLSv1.2 in a secure way. There is A+ on https://cryptcheck.fr/https/search.fshm.in 

Regarding filtron, I think it working as intended as it has definitely blocked spam as shown below in the picture.
![image](https://user-images.githubusercontent.com/6304985/112035239-5b9e7080-8b65-11eb-945e-a33c90b9dba2.png)

Regarding the JSON test, https://github.com/searx/searx-docker/blob/master/rules.json#L114 the rate limit is set at 3600, maybe it is to accommodate the infinite scroll feature of SearX? However the default setting for JSON in filtron is 121 ( https://github.com/searx/searx/blob/master/utils/templates/etc/filtron/rules.json#L99 )

**Comment by unixfox** [comment]
Good job on the TLS security!

There is still one issue:

I'm being blocked on https://search.fshm.in/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json after 5 retries but not on https://search.fshm.in/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json.

The solution is to change the base_url in Searx settings so that the root path (`/`) is used but not `/searx` and stop exposing Searx on the sub path`/searx`.
This URL should lead to a 404 error page: https://search.fshm.in/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

**Comment by dalf** [comment]
> maybe it is to accommodate the infinite scroll feature of SearX?

the infinite scroll fetches HTML pages not JSON.

```
                "interval": 3600,
                "limit": 4,
```

means no more than 4 requests per hour from the IP. 
On a public instance, it avoids abuse from the bots (at least some of them).

**Comment by unixfox** [comment]
Closing as search.fshm.in doesn't serve any searx instance anymore.
