### ISSUE TITLE
Add https://start.paulgo.io

### ISSUE THREAD

**Issue by MrPaulBlack** [searx/searx-instances#145]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

I changed some css and a few images for the static theme; here is my source code under the same license:

https://github.com/paulgoio/searx

**Comment by unixfox** [comment]
Hello, filtron is not properly installed. I'm able to do a lot of requests per seconds which is not good in order to reduce the likeness of your instance being blocked by the engines. You should use these rules: https://github.com/searx/searx-docker/blob/master/rules.json

This is just a recommendation but if you don't want to tweak your rules I can still add your instance anyway.

**Comment by MrPaulBlack** [comment]
Hi, in switched to dalf/filtron:latest with https://github.com/searx/searx-docker/blob/master/rules.json rules applied. Please go ahead with adding my instance and thank you.
