### ISSUE TITLE
Offer a different submission option

### ISSUE THREAD

**Issue by tacerus** [searx/searx-instances#149]
Hi,

I appreciate your services, however wonder how being directed to GitHub helps in providing anonymous searx instances. Providers wanting to ensure full anonymity for their users are unable to do so if a GitHub accounts refers back to them.

I suggest the implementation of a submission form that is accessible directly from your instance site, which is already accessible anonymously through Tor.

Cheers,
Georg

**Comment by unixfox** [comment]
That's a very good idea, but we tend to prefer GitHub because it allows us to contact the maintainer in case of issues with his instance.
I think I wouldn't mind creating an email address for submitting instances, but the issue is that this process would be private, and I like the idea of having open submissions like on GitHub where everyone can see and react to them.
Not sure if there are other ways of submitting public posts without having to create an account, maybe something like 4chan...

**Comment by return42** [comment]
my 2cent: I think the idea is to protect privacy of the user not of the provider.  At least the domain under which a service is provided needs contact data. We also encourage providers to  set a [contact_url](https://searxng.github.io/searxng/admin/engines/settings.html#global-settings).

>  if a GitHub accounts refers back to them.

IMO that is the real drawback, that a github account is needed to participate.  There are a lot of _DevOps_ out there who leaved github for their own good reasons.

**Comment by tacerus** [comment]
By leaking privacy of the provider, indirectly users are being affected too. Whilst not always having to be the case, an infiltrated instance operator could feel pressured to leak users data for their own safety. If the instance operator themselves remain anonymous however, this situation cannot occur in the first place.

Since you prefer to gather things on GitHub, possibly something in the direction of this (not tested) could be of interest:
https://gist.github.com/travstoll/d6d72855b4184fbfc30f3a20a9adbb4c

**Comment by unixfox** [comment]
> Since you prefer to gather things on GitHub, possibly something in the direction of this (not tested) could be of interest:
> [gist.github.com/travstoll/d6d72855b4184fbfc30f3a20a9adbb4c](https://gist.github.com/travstoll/d6d72855b4184fbfc30f3a20a9adbb4c)

We aren't going to do something like that because without any restriction, the associated GitHub account with an access token could get his account banned/blocked due to potential spam/bad actors sending emails to the email address. I have no desire to spend my time to introduce a system that filter spams/bad actors.

It's a good idea, but I would prefer a separate platform which is not related to GitHub. I don't really mind having to check it out from time to time.

**Comment by tacerus** [comment]
A seperate platform, possibly integrated with the directory page, would of course be even better.

**Comment by return42** [comment]
> Which can be an anonymous email address, no?

It does not have to be an email address, it is an optional URL.

**Comment by unixfox** [comment]
Moving the discussion to the searxng repo: https://github.com/searxng/searx-instances/issues/75
