### ISSUE TITLE
Add https://search.riverside.rocks

### ISSUE THREAD

**Issue by RiversideRocks** [searx/searx-instances#170]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://search.riverside.rocks/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

This is just an advice and if you don't want to follow it I can add your instance anyway.

Also, peoples in the privacy community don't like cloudflare so be advised that your instance is going to get less traffic to due to that.

**Comment by RiversideRocks** [comment]
I'll play with the bot rules. I'm not the biggest Cloudflare fan, but my website from time to time is targeted by DDoS attacks so I need to have it on.

**Comment by unixfox** [comment]
Any updates on the progress of improving your filtron rules?

**Comment by unixfox** [comment]
Closing due to a lack of replies.

If needed reopen with the answer to my question.
