### ISSUE TITLE
Add https://search.razorserver.fr/

### ISSUE THREAD

**Issue by Razorbackfr** [searx/searx-instances#178]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://search.razorserver.fr/search?category_general=1&q=ok&pageno=1&time_range=None&language=en-US&format=json

You may use these filtron rules instead: https://github.com/searx/searx-docker/blob/master/rules.json

Also, your instance is **very slow**, the engines are often timing out. If you have a low spec Linux server and/or not enough bandwidth, I don't recommend you to be listed as a public instance because your instance is going to suffer to the point that it won't respond anymore.

**Comment by unixfox** [comment]
Closing due to a lack of replies.

Please reopen after answering to my questions.
