### ISSUE TITLE
move repository to SearXNG group

### ISSUE THREAD

**Issue by return42** [searx/searx-instances#186]
This repository can be moved to the [SearXNG group](https://github.com/searxng) where [searx.space](https://github.com/searxng/searx-space) is already maintained.

**Comment by unixfox** [comment]
We already discussed about it with dalf.

I don't have the access for that, only asciimoo as it.

**Comment by unixfox** [comment]
Request sent to asciimoo, waiting for his reply.

**Comment by asciimoo** [comment]
Why don't you fork this repo to be under your organization, just like you did with searx?

**Comment by unixfox** [comment]
Hi @asciimoo, not sure if you saw my email or not but I'll reiterate what I said in it here.

The repository searx-stats2 aka [searx-space](https://github.com/searxng/searx-space) got migrated to SearXNG because dalf is still improving searx.space and he wasn't able to make changes on the GitHub repository when it was under the SearX organization.

We think it makes more sense to move the SearX instances list to SearXNG as this is directly related to searx.space which is now managed under the SearXNG GitHub organization.

If you accept my request, could you make me Admin of this GitHub repository so that I'm capable of moving it to SearXNG?

**Comment by unixfox** [comment]
@asciimoo Any update on this matter?

**Comment by unixfox** [comment]
Closing, as I made the decision of creating a copy there: https://github.com/searxng/searx-instances.
