### ISSUE TITLE
https://searx.akusov.xyz

### ISSUE THREAD

**Issue by akusoff** [searx/searx-instances#215]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://searx.akusov.xyz/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=fr&format=json

You will probably need to fix your filtron rules.

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by akusoff** [comment]
Hello. I've copied rules from this example: https://github.com/searx/searx-docker/blob/master/rules.json. Isn't enough to make filtron work properly? Shoul I change something in it?

**Comment by unixfox** [comment]
I think it's related to the fact that you are serving searx from the path /searx. I think you should change that so that it is served directly from the root path aka /.

**Comment by akusoff** [comment]
Where can I find this kind of configuration? Root path in nginx is /.  Where else can I look to change serving path?

**Comment by unixfox** [comment]
I'm unfortunately not familiar with the official setup of searx with NGINX.

Maybe you need to edit the nginx files in /etc/nginx.

Do note though that if you don't really know anything about NGINX and (linux in general) I don't recommend hosting a public searx instance  because there are a lot of bad actors that will try to abuse your instance and you won't be able to stop them. This will thus decrease the usability/stability of your searx instance.

**Comment by akusoff** [comment]
I've found string in nginx conf I needed! Now it looks like filtron protection should work properly. Could you check it?

**Comment by unixfox** [comment]
It's now working fine, I've added your instance.

**Comment by akusoff** [comment]
Thank you!
