### ISSUE TITLE
Add https://searx.sadblog.xyz

### ISSUE THREAD

**Issue by inugami-dev64** [searx/searx-instances#218]
### General

- [X] It is my instance.
- [X] I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

### Bot protection

Yes, I have installed filtron (rules.json from searx-docker).

**Comment by unixfox** [comment]
Hello,

Your filtron rules are not optimal, I'm able to do an infinite amount of requests (more than 5 requests) on the JSON results: https://searx.sadblog.xyz/searx/search?category_general=1&q=ok&pageno=1&time_range=None&language=fr&format=json

You will probably need to fix your filtron rules and stop serving searx from the path /searx in order to have the filtron rules working.

This is just an advice and if you don't want to follow it I can add your instance anyway.

**Comment by inugami-dev64** [comment]
Hello. Filtron rate limits should be working correctly now, you can add the instance.
