### ISSUE TITLE
Add https://searx.pleasecuminside.me

### ISSUE THREAD

**Issue by b053f81f** [searx/searx-instances#90]
* [x] It is my instance.
* [x] I give the right to searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests).

Pick one:
* [x] I have installed [filtron](https://github.com/asciimoo/filtron/), [antibot-proxy](https://github.com/unixfox/antibot-proxy) or another bot protection.
* [ ] I do recognize that without a bot protection, my instance will be flooded by bots and could have some of its engines stop working (an example is Google).

**Comment by resynth1943** [comment]
I agree

**Comment by yurihentai** [comment]
@dalf @unixfox 
You probably may find it too embarrassing to add this domain onto the searx instance list, but you also cannot find a good reason to deny this issue. Consequentially this issue with the dirty name sits at the top of the issue tracker.

I personally would approve this issue and add the instance on the list. It's nothing more than a string; a url, a name, words, with no serious message. It's just as intelligible as something like "searx.fmac.xyz". It's not particularly offensive nor does it carry any political or opinionated message or agenda.

In the spirit of GNU and free software, by Stallman's beard I would add this instance, this instant. It would be reminiscent of a nonfree authority such as Google, for a single authoritarian figure to utterly deny freedom that this man deserves. What would people think of the Searx project if they just deny proper, well-functioning instances from the instance list as they please? This issue, if denied, would live in infamy. And if approved, then people would see the Searx project as an open-minded group of devs who truly care about freedom and decentralization.

**Comment by resynth1943** [comment]
Agreed. I'd like to see this too. As Americans, we need to lay the foundation for frameworks which encourage freedom of speech and self-expression.

Furthermore, there are fundamental issues with denying such an effervescent addition: this domain is an art form, which is reinforced by the social aspects of said author. By refusing such an addition, we would be damaging GitHub as a whole. Software development relies on the open minds of every individual. 

Likewise, as good Samaritans, freedom of recognition is also to be desired in an open-source community. This instance has clearly been licensed by the author, which allows him to share his joyous creation with impunity. I believe adding this URL to the list would greatly influence the current political landscape, which denies freedom of education to lowly citizens like myself.

As candidates for a free, decentralised network ("Series of Nodes"), it would certainly sway the powerful message this project carries. Such a resource must be open to appending art forms by external entities. Otherwise, it would be a heavily biased (and factually incorrect) source of information.

I *strongly* suggest you add this instance.

**Comment by godo-chan** [comment]
I really can't compete with the other comments. Anything I would say in addition would just water down the strong message about the importance of adding this domain. I can only say, as a trans PoC, that this website has been a symbol of freedom of expression for me any many of my peers, and having a searx instance would not only make it easier for us to use it, but would also send a strong message about how searx views minority groups and their freedoms.

**Comment by xx1182** [comment]
You guys do understand that this is not "freedom of speech" but rather respect.

You can't name your son "PussyDestroyer", simply cause of respect, think of the istances as son of the main one.

I really really like to piss myself, but i do understand that i can't go out in public with piss pants... it's my freedom to piss myself, it's my freedom to go around with my pants pissed, but it's respect to not piss myself at a funeral.

**Comment by dalf** [comment]
Sorry for the delay.

We don't want searx to be associated with NSFW content.
We _may_ support a NSFW list in the future in a way or another.
For now, we won't accept this instance name.

**Comment by resynth1943** [comment]
I feel overwhelming empowered by the stories shared here. Brought a smile to my face.

**Comment by xx1182** [comment]
To not.
Then im getting mine back

Il Gio 15 Ott 2020, 15:09 Alexandre Flament <notifications@github.com> ha
scritto:
